### ISSUE TITLE
7.5: Draft a rough project plan

### ISSUE THREAD

**Issue by hellodommy** [AY1920S1-CS2103T-T12-3/main#9]
**[Step 5](https://nus-cs2103-ay1920s1.github.io/website/schedule/week7/project.html#5-draft-a-rough-project-plan) of Week 7 increments:**

- [x] Decide which features each member will do by v1.4
- [x] Divide each of those features into two increments, to be released at v1.2, v1.3 (v1.4 omitted deliberately as a buffer). **Each increment should deliver a end-user visible enhancement.**
- [x] Record the project plan in the issue tracker (create new issues if necessary) by assigning issues to the relevant team member and the relevant milestone.
